package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.Exam;
import greendao.Ranking;
import greendao.Question;
import greendao.Answer;
import greendao.Progress;

import greendao.ExamDao;
import greendao.RankingDao;
import greendao.QuestionDao;
import greendao.AnswerDao;
import greendao.ProgressDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig examDaoConfig;
    private final DaoConfig rankingDaoConfig;
    private final DaoConfig questionDaoConfig;
    private final DaoConfig answerDaoConfig;
    private final DaoConfig progressDaoConfig;

    private final ExamDao examDao;
    private final RankingDao rankingDao;
    private final QuestionDao questionDao;
    private final AnswerDao answerDao;
    private final ProgressDao progressDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        examDaoConfig = daoConfigMap.get(ExamDao.class).clone();
        examDaoConfig.initIdentityScope(type);

        rankingDaoConfig = daoConfigMap.get(RankingDao.class).clone();
        rankingDaoConfig.initIdentityScope(type);

        questionDaoConfig = daoConfigMap.get(QuestionDao.class).clone();
        questionDaoConfig.initIdentityScope(type);

        answerDaoConfig = daoConfigMap.get(AnswerDao.class).clone();
        answerDaoConfig.initIdentityScope(type);

        progressDaoConfig = daoConfigMap.get(ProgressDao.class).clone();
        progressDaoConfig.initIdentityScope(type);

        examDao = new ExamDao(examDaoConfig, this);
        rankingDao = new RankingDao(rankingDaoConfig, this);
        questionDao = new QuestionDao(questionDaoConfig, this);
        answerDao = new AnswerDao(answerDaoConfig, this);
        progressDao = new ProgressDao(progressDaoConfig, this);

        registerDao(Exam.class, examDao);
        registerDao(Ranking.class, rankingDao);
        registerDao(Question.class, questionDao);
        registerDao(Answer.class, answerDao);
        registerDao(Progress.class, progressDao);
    }
    
    public void clear() {
        examDaoConfig.getIdentityScope().clear();
        rankingDaoConfig.getIdentityScope().clear();
        questionDaoConfig.getIdentityScope().clear();
        answerDaoConfig.getIdentityScope().clear();
        progressDaoConfig.getIdentityScope().clear();
    }

    public ExamDao getExamDao() {
        return examDao;
    }

    public RankingDao getRankingDao() {
        return rankingDao;
    }

    public QuestionDao getQuestionDao() {
        return questionDao;
    }

    public AnswerDao getAnswerDao() {
        return answerDao;
    }

    public ProgressDao getProgressDao() {
        return progressDao;
    }

}
