package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PROGRESS.
 */
public class Progress {

    private Long id;
    private Long examId;
    private Long examDuration;
    private Long answeredQuestionId;
    private Integer totalRightAnswers;
    private Integer totalWrongAnswers;
    private String startDate;
    private String endDate;

    public Progress() {
    }

    public Progress(Long id) {
        this.id = id;
    }

    public Progress(Long id, Long examId, Long examDuration, Long answeredQuestionId, Integer totalRightAnswers, Integer totalWrongAnswers, String startDate, String endDate) {
        this.id = id;
        this.examId = examId;
        this.examDuration = examDuration;
        this.answeredQuestionId = answeredQuestionId;
        this.totalRightAnswers = totalRightAnswers;
        this.totalWrongAnswers = totalWrongAnswers;
        this.startDate = startDate;
        this.endDate = endDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getExamId() {
        return examId;
    }

    public void setExamId(Long examId) {
        this.examId = examId;
    }

    public Long getExamDuration() {
        return examDuration;
    }

    public void setExamDuration(Long examDuration) {
        this.examDuration = examDuration;
    }

    public Long getAnsweredQuestionId() {
        return answeredQuestionId;
    }

    public void setAnsweredQuestionId(Long answeredQuestionId) {
        this.answeredQuestionId = answeredQuestionId;
    }

    public Integer getTotalRightAnswers() {
        return totalRightAnswers;
    }

    public void setTotalRightAnswers(Integer totalRightAnswers) {
        this.totalRightAnswers = totalRightAnswers;
    }

    public Integer getTotalWrongAnswers() {
        return totalWrongAnswers;
    }

    public void setTotalWrongAnswers(Integer totalWrongAnswers) {
        this.totalWrongAnswers = totalWrongAnswers;
    }

    public String getStartDate() {
        return startDate;
    }

    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    public String getEndDate() {
        return endDate;
    }

    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

}
